version: '3.5'

services:
  jenkins:
    build:
      context: .
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - "jenkins_home:/var/jenkins_home"
      - "./jenkins-cli.jar:/var/jenkins_home/jenkins-cli.jar"
      - "/var/run/docker.sock:/var/run/docker.sock"
#      - "/usr/bin/docker:/usr/bin/docker"
    networks:
      jenkins_nexus:
       
  nexus:
    image: sonatype/nexus3:3.51.0
    container_name: nexus
    restart: unless-stopped
    ports:
      - "8081:8081"
      - "8085:8085"   
    volumes:
      - "nexus_data:/nexus-data"
    networks:
      - jenkins_nexus
    environment:
      TZ: "/etc/timezone"

networks:
  jenkins_nexus:
#    network_mode: host
#    driver: bridge
#    internal: false
#    ipam:
#      driver: default
#      config:
#        - subnet: 100.127.255.0/24


volumes:
  jenkins_home:
  nexus_data:
